apiVersion: v1
kind: Namespace
metadata:
  name: go-web-example

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-web-example
  name: go-web-example
  namespace: go-web-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-example
  template:
    metadata:
      labels:
        app: go-web-example
    spec:
      containers:
      - image: petrolnt/web-v1:latest
        name: web-v1
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 80
#          initialDelaySeconds: 10
#          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: go-web-svc
  namespace: go-web-example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: go-web-example

